origins:
  - namespace: cert-manager-namespace  # The namespace where Cert-Manager is installed
    secrets:
      - secret: dummy-secret            # Name of the secret to monitor
        destinations:
          - tri                        # Change namespace1 to tri
          - sra                        # Change namespace2 to sra
